module.exports = {
	phrases: [
'Aby być mądrym, nie wystarczy mieć wiele ksiąg: osioł dźwigający na grzbiecie wiele książek nie jest przez to mądrzejszy.',
'Aby kochać psim sercem, trzeba patrzeć boskimi oczami.',
'Aby umiłować pokój, trzeba być głuchym, ślepym i niemym.',
'Aforyzmy to lśniące wśród mroków latarnie.',
'Ambicją sięgamy wyżej nieba, ale los nasz jest cieńszy od papieru.',
'Ani drogi do nieba, ani bramy do ziemi.',
'Bądźcie surowi dla siebie samych, pobłażliwi dla innych, a nie będziecie mieli wrogów.',
'Bez odwagi nie zostaniesz dowódcą.',
'Bezużyteczną rzeczą jest uczyć się, lecz nie myśleć, a niebezpieczną myśleć, a nie uczyć się niczego.',
'Biedny boi się krewnych, a bogaty złodziei.',
'Bij swoje dziecko raz na dzień. Jeżeli ty nie wiesz za co, ono na pewno wie.',
'Bijąc psa, obrażasz jego pana.',
'Biorąc strój nowy, zapomnij o starym.',
'Błąd chwili staje się troską całego życia.',
'Błąd leży w pośpiechu.',
'Bogatemu diabli na żarnach mielą.',
'Brama dobroczynności trudno się otwiera i trudno zamyka.',
'Bramy urzędu są dla wszystkich szeroko otwarte, ale nie można tam wejść bez pieniędzy.',
'Brzydka kobieta jest skarbem w domu, ale na ucztach króluje piękna.',
'By nie móc nawet spojrzeć na wódkę – trzeba spojrzeć na pijaka.',
'Choć droga niedaleka, nie dojdziesz, jeśli do celu nie zmierzasz.',
'Chcąc poznać wszystkie sprawy świata, czytajcie księgi starożytne.',
'Chciwy zostanie kupcem, a leniwy mnichem.',
'Choroba jest uleczalna, nie przeznaczenie.',
'Ci, co mordują i podpalają, zawsze są syci, a ci, co czytają teksty i powtarzają imię Buddy, są zawsze głodni.',
'Ciągle musimy się bać: w młodości ojca i nauczyciela; w męskim wieku prawa i nieszczęścia; na starość śmierci.',
'Cielęta nie boją się tygrysa.',
'Cnota zdobi ciało, bogactwo izbę.',
'Co dziesięć mil nawyki się zmieniają, a co sto – nawet obyczaje są zupełnie różne.',
'Co jawnie darujesz, potajemnie będzie ci zwrócone.',
'Co roku trzeba się zabezpieczać przeciw klęsce głodu, a złodziei strzec się trzeba co dzień,',
'Co z lemiesza, który nie wzrusza ziemi, co z paliwa, które tłamsi ogień?',
'Cywilny minister może uspokoić kraj, a generał – założyć nową dynastię,',
'Czas kosztuje złoto, ale i za złoto czasu nie kupisz,',
'Czego oczy nie widzą, o to serce nie boli, czego uszy nie słyszą, to ich nie oburza.',
'Człowiek bez uśmiechniętej twarzy nie powinien otwierać sklepu.',
'Człowiek całe życie prześpi, jeśli wierzy w swoje sny.',
'Człowiek codziennie doprowadza swoje włosy do porządku. Dlaczego jednak nie serce?',
'Człowiek honoru mści się nawet po dziesięciu latach.',
'Człowiek nie powinien schodzić z drogi, a tygrys – opuszczać górskich stepów.',
'Człowiek nie wie, kiedy umrze, a wóz – kiedy się wywróci.',
'Człowiek raz ugryziony przez węża nie chce chodzić po trawie.',
'Człowiek, który mówi: tego się nie da zrobić, nie powinien przeszkadzać TEMU, który TO robi.',
'Czytaj jak najwięcej, mów jak najmniej.',
'Czytasz jakąś książkę po raz pierwszy, poznajesz nowego przyjaciela; czytasz ją po raz drugi, spotykasz starego.',
'Dla mężczyzny cnota jest talentem, dla kobiet brak talentów jest cnotą.',
'Dla przechodniów bądź gościnnym, dla sąsiadów – pomocnym, dla poczciwych – przyjacielem, dla złych – obcym.',
'Długa choroba rodziców zniechęci najbardziej przywiązanego syna.',
'Długo szuka się przyjaciela, szybko się go traci.',
'Do wróbla nie strzela się z armat.',
'Dobre lekarstwo jest gorzkie w ustach, ale skuteczne w chorobie.',
'Dobre przypadki zdarzają się zwykle tym, którzy mają wiele optymizmu.',
'Dobre serce to jest Budda.',
'Dobrzy są ludzie starzy, a ubrania – nowe.',
'Dobrzy szukają się wzajemnie, ale źli stronią od siebie.',
'Dopiero ze szczytu góry można ocenić rozległość równiny.',
'Dowódca nie powinien nigdy zsiadać z konia.',
'Drapieżniki łowi się podstępem, zwierzęta domowe – arkanem.',
'Drogą wiodącą do nieba nikt nie dąży, a choć piekło nie ma bramy, wszyscy doń szturmują.',
'Drogocenne szable daje się bohaterom, a noże cnotliwym niewiastom.',
'Duchy zmarłych radują się jedynie z ofiar składanych przez potomków.',
'Dzieci trzeba pouczać publicznie, a żonę prywatnie.',
'Gdy los się nam uśmiecha, spotykamy przyjaciół, a gdy nam jest przeciwny, ładną kobietę.',
'Gdy ludzie są sobie przyjacielscy, nawet woda staje się słodka.',
'Gdy mężczyźni zejdą się razem, to się słuchają; kobiety zaś nawzajem się oglądają.',
'Gdy nie kwitną ci jabłonie, nie jest to wina słońca.',
'Gdy nie masz nic do ofiarowania, ofiaruj uśmiech.',
'Gdy sąsiad wszedł do twego sadu, niedostrzeganie go jest najprawdziwszą grzecznością.',
'Gdy wieją wichry zmian, jedni budują mury, inni budują wiatraki.',
'Gdy wilkołak zamienia się w człowieka, ogon zawsze mu pozostaje.',
'Gdy za dużo murarzy, dom staje się krzywy.',
'Gdy zbyt pełno w czarce – łatwo o przelanie.',
'Gdyby człowiek posiadł wytrwałość, nic nie byłoby niemożliwe.',
'Gdzie kobiety są czczone, tam radują się bogowie; tam gdzie nie są czczone, wszystkie praktyki religijne pozostają bez skutku,',
'Gdzie urzędnik bije lud, ojciec syna, a mąż żonę – tam nie ma wstydu,',
'Generał w polu nie słucha cesarza.',
'Głodnemu daj kawałek chleba, ale smutnemu daj kawałek twego serca.',
'Głupia synowa i nieposłuszny syn są jak czad i sadza.',
'Gościowi, który zostaje najdłużej, ginie płaszcz.',
'Góra Tai nie odrzuca najmniejszego pyłku i dlatego jest taka wysoka.',
'Góry wysoko, a cesarz daleko',
'Grzech zatruwa rozkosz, namiętność ją niszczy, umiarkowanie zaostrza, niewinność oczyszcza, czułość podwaja.',
'Hazard jest bliski kradzieży, a cudzołóstwo jest bramą morderstwa.',
'I ogień, i woda są nieczułe na ludzkie cierpienia.',
'I tygrys nosi różaniec, żeby uchodzić za dobrotliwego.',
'Im głębsza noc, tym bliżej świtu.',
'Im kto biedniejszy, tym więcej diabłów za nim się ugania.',
'Im więcej praw, tym więcej złodziei.',
'Im większe drzewo, tym większy cień rzuca.',
'Istnieje tylko dwóch dobrych ludzi – jeden zmarł, a drugi się jeszcze nie narodził.',
'Jak w jasnym zwierciadle można poznać kształty, tak z przeszłości można poznać teraźniejszość.',
'Jakie pszczoły, taki miód.',
'Jeden dom dobrze ogrzany i zaopatrzony wzbudza zazdrość mieszkańców tysiąca innych.',
'Jeden klucz nie robi hałasu, ale już dwa klucze brzęczą.',
'Jeden obraz wart więcej niż tysiąc słów.',
'Jedna noc rozmowy z mędrcem starczy na dziesięć lat studiów.',
'Jedno drzewo nie tworzy lasu.',
'Jeśli chcesz mi pomóc, nie każ mi czekać w kuchni.',
'Jeśli człowiek sam się nie pilnuje, to Niebo i Ziemia zniszczą go',
'Jeśli garnek nie jest zbity, przez cały wiek nie będzie przeciekał.',
'Jeśli jeden syn wstąpi do klasztoru, to dziewięć pokoleń pójdzie do nieba.',
'Jeśli każdy otrzyma swoje, diabeł nie otrzyma nic.',
'Jeśli kto przez całe życie poluje na dzikie gęsi, w końcu mu dzika gęś oko wydłubie.',
'Jeśli ktoś oszuka ziemię, to i ziemia go oszuka.',
'Jeśli ktoś przez dziesięć lat miał szczęście, to ani duchy, ani upiory nie ośmielą się go zaczepić.',
'Jeśli to nie przeznaczenie, to nawet jeśli dwoje się spotka, nie zaznajomią się.',
'Jeśli nie słuchasz rodziców, czyż nie będą daremne twoje dobre uczynki?',
'Jeśli nie szanujesz bogów, to słuchaj głosu gromu.',
'Jeśli rozrzucasz ciernie, nie chodź bez butów.',
'Jeśli się nikogo o nic nie prosi, wszyscy wydają się uczynni,',
'Jeśli zdobędziesz się na cierpliwość w jednej chwili gniewu, zaoszczędzisz sobie sto dni przykrości.',
'Jeśliś za życia nie chodził po urzędach, po śmierci nie dostaniesz się do piekła.',
'Jeżeli 50-letniego mężczyznę po przebudzeniu nic nie boli, to znaczy, że ten mężczyzna nie żyje.',
'Jeżeli chcesz pożegnać się z winem, przyjrzyj się pijakowi.',
'Jeżeli jeden syn pójdzie do klasztoru, to dziewięć pokoleń pójdzie do nieba.',
'Jeżeli ktoś ma szczęście, to i niebo mu dopomaga.',
'Jeżeli nie przyznajesz się do błędu, to popełniasz błąd drugi.',
'Jeżeli odrzucisz nóż rzeźnika, natychmiast staniesz się Buddą.',
'Jeżeli skrzywdzona kobieta się uśmiecha wobec krzywdziciela, to albo nie ma wstydu, albo jest pewna, że się dobrze zemścić potrafi.',
'Jeżeli strzelec spudłuje, niechaj tylko w sobie samym szuka przyczyny swego niepowodzenia.',
'Jeżeli twierdzisz, że tygrys jest krową, to spróbuj go wydoić.',
'Jeżeli w domu czcisz rodziców, nie potrzebujesz chodzić daleko, żeby palić kadzidło.',
'Jeżeli zbłądzisz, nie oskarżaj o to nieba, jeżeli się potkniesz, nie oskarżaj o to ziemi.',
'Jeżeli żona wie, co się dzieje poza domem, mąż nie wie, co się dzieje w domu.',
'Język jest bronią kobiet, nigdy nie pozwalają jej zardzewieć.',
'Język kobiety jest krótki, ale rani mężczyznę bardzo głęboko.',
'Językiem można zmiażdżyć człowieka.',
'Kapłan może uciec, ale świątynia musi zostać.',
'Kapłan może wprowadzić cię do świątyni, ale ćwiczenie się w cnocie należy do ciebie.',
'Każda droga prowadzi do Pekinu.',
'Kiedy człowiek kroczy drogą Środka, nawet jego zwierzęta wstępują do Nieba',
'Każdy człowiek ma przed swymi drzwiami kawałek nieba.',
'Każdy dobry uczynek ma swoją nagrodę.',
'Każdy dowódca ma swój sposób rozkazywania, a każdy nauczyciel swój sposób rzezania.',
'Każdy krok zostawia ślad.',
'Każdy towar ma swoją cenę.',
'Kiedy jeden głos odezwie się z pałacu, sto głosów z dołu będzie mu potakiwać,',
'Kiedy jesz rybę, nie skarż się na jej zapach.',
'Kiedy pierwszy wóz staje, karawana się zatrzymuje.',
'Kiedy piękna kobieta do ciebie mówi, uśmiechnij się, ale jej nie słuchaj.',
'Kiedy robisz łaskę, nie licz na nagrodę, kiedy szukasz nagrody, nie wyrządzasz łaski.',
'Kiedy się nikogo o nic nie prosi, wszyscy wydają się uczynni.',
'Kiedy spotyka cię łaska, myśl o przyszłej zniewadze, a w czasie spokoju, pamiętaj o niebezpieczeństwie.',
'Kiedy starosta jest uczciwy, to gońcy w starostwie są chudzi, kiedy świątynia ma cudowny posąg, to opat jest tłusty.',
'Kiedy w spokojnych czasach nie pali się Buddzie trociczek, to w chwilach niebezpieczeństwa łapie się Buddę za nogę.',
'Kobieta jest jak zły mandaryn. Im bardziej odstępuje od dobrych zasad, tym gorliwsza jest w słowach.',
'Konie nadziei pędzą galopem, natomiast osły doświadczenia jadą stępa.',
'Kop studnię, zanim będziesz miał pragnienie.',
'Kruki wszędzie są czarne.',
'Książka jest jak ogród noszony w kieszeni.',
'Książka jest niczym ogród, który można włożyć do kieszeni.',
'Książki nie zawierają wszystkich słów, słowa nie zawierają wszystkich myśli.',
'Kto częstuje złym winem, tego poczęstują tylko herbatą.',
'Kto kocha żonę, nie pyta, czy kochać ją powinien.',
'Kto ma na języku miód, często ukrywa pod nim piołun.',
'Kto ma pieniądze jest smokiem, kto ich nie ma – jest robakiem.',
'Kto ma pieniądze, może zmusić diabła, by napędzał jego młyn.',
'Kto ma piękniejszą żoną, zamek na granicy, winnicę przy drodze, ten nigdy wojny nie skończy.',
'Kto ma w domu miliony, nie ma chwili spokoju.',
'Kto nie karmi psa, karmi złodzieja.',
'Kto nie myśli o jutrze, będzie miał kłopoty, zanim dziś się skończy.',
'Kto otwiera swe serce dla ambicji – zamyka je przed spokojem.',
'Kto pyta, jest głupcem przez pięć minut; kto nie pyta, pozostaje nim do końca.',
'Kto raz wsiadł na tygrysa, nie może już z niego zsiąść.',
'Kto się nie zląkł fali wielkiej rzeki, niech się nie obawia spokojnych wód kanału.',
'Kto szuka przyjaciela bez wad, pozostanie bez przyjaciela.',
'Kto twoje złe postępki życzliwie gani, czyni jak ten, kto błądzącemu dobrą drogę wskazuje.',
'Kto uczył cię tylko jeden dzień, jest ci ojcem na całe życie.',
'Kto zasłania uszy, kradnąc dzwon ze świątyni, oszukuje sam siebie.',
'Kto zbyt wiele mówi, rzadko bywa szczery.',
'Kto zna swoją głupotę, nie jest wielkim głupcem.',
'Kto żywi się owocami, będzie bezsilny; kto żywi się mięsem, będzie dzielny; kto żywi się ryżem, będzie mądry; kto żywi się powietrzem, będzie święty.',
'Kwiat lotosu, liść lotosu i nasienie lotosu wychodzą z jednego korzenia. Trzy nauki pochodzą z jednej i tej samej rodziny.',
'Kwiaty sztucznie sadzone źle rosną, a dziko rosnąca wierzba najwięcej cienia daje.',
'Lek nie uleczy zmyślonej choroby, a wódka nie uleczy prawdziwego smutku.',
'Lekarstwo nie uleczy zmyślonej choroby, a wino nie rozproszy prawdziwego zmartwienia.',
'Lekarz może wyleczyć z choroby, ale nie z losu.',
'Lenistwo rodzi bezsilność.',
'Lepiej być jeden dzień żywym człowiekiem niż tysiąc dni upiorem.',
'Lepiej być niegrzecznym niż nieposłusznym.',
'Lepiej jest wzbogacać swych wrogów po śmierci, niż przyjaciół potrzebować za życia.',
'Lepiej rozkazywać sobie niż innym, lepiej sobie pomagać niż szukać pomocy u innych.',
'Lepiej uratować jedno ludzkie życie niż zbudować siedmiopiętrową pagodę.',
'Lepiej z mądrym umierać, niż żyć z głupim.',
'Lepiej zapalić świeczkę, niż narzekać na ciemność.',
'Literatura jest krajobrazem na biurku, a krajobraz jest literaturą na ziemi.',
'Los pięknych kobiet jest nieszczęśliwy, wybitni mężczyźni rzadko bywają urodziwi.',
'Lód o grubości trzech stóp nie bierze się z jednego chłodnego dnia.',
'Ludzie i zwierzęta należą do tej samej kategorii istot.',
'Ludzie na starość stają się bezużyteczni; stare przedmioty stają się cennymi zabytkami.',
'Ludzie, chociaż nie dożyją nawet stu lat, to jednak stwarzają sobie troski na całe tysiąclecia.',
'Lustro naprawdę gładkie nie zatrzymuje pyłu; w światłym sercu nie powstają żądze.',
'Łatwo przywołać duchy, trudno je odegnać.',
'Mając jedzenia do syta i fajkę pełną tytoniu, jest się równym bogom nieśmiertelnym.',
'Maksymy mędrców i świętych szanują bogowie, a demony są im posłuszne.',
'Mała niecierpliwość burzy wielkie plany.',
'Małe zyski psują wielkie interesy.',
'Małpa bez ogona to i tak tylko małpa.',
'Małpa ubrana w czapkę przypomina człowieka.',
'Mały błąd może być przyczyną wielkiego smutku.',
'Małżeństwa są postanowione w niebie.',
'Mądra pszczoła nie pije ze zwiędłego kwiecia.',
'Mądremu wystarczy napomknąć, a głupiego nawet biciem się nie nauczy.',
'Mądry człowiek nie chce przewyższać cesarza, a rozsądny nie chce wywyższać się nad kanclerza.',
'Mądry mężczyzna potrafi zbudować miasto, mądra kobieta jest zdolna doprowadzić do jego upadku.',
'Mądry przez całe życie może zgłupieć na chwilę.',
'Mężczyzna uważa, że wie, ale kobieta wie lepiej.',
'Milczeniem nigdy sobie kobieta sprawy nie popsuła.',
'Mnichowi dobrze się wiedzie w stolicy, a urzędnikowi na prowincji.',
'Mogę zapomnieć, o czym usłyszałem, albo zachować w pamięci to, co zobaczyłem. To, co zrobiłem, mogę zrozumieć.',
'Mord może być wybaczony, niegrzeczność nigdy.',
'Można usunąć skazę w klejnocie, ale nie można cofnąć powiedzianego słowa.',
'Można utopić rozum w winie, ale nieszczęścia utopić się nie da.',
'Mówiąc tysiąc słów, trudno sobie nie zaszkodzić.',
'Na dziesięć kobiet dziewięć jest zazdrosnych.',
'Nadmiar grzeczności nikogo nie obrazi.',
'Nadzy się rodzimy i nadzy odchodzimy.',
'Nauka, która trafia do uszu, lecz nie do serca, jest jak obiad jedzony w marzeniach.',
'Najlepszy koń się potknie, najlepszy pływak może utonąć.',
'Najostrzejsza siekiera sama przez się nie zabije przechodzącego człowieka.',
'Najostrzejszy miecz nie zetnie niewinnej głowy.',
'Najwięcej czasu ma człowiek, który niczego na później nie odkłada.',
'Najwięcej kłamie ten, kto najwięcej mówi o sobie.',
'Najwięcej rozumu trzeba wtedy, gdy ma się do czynienia z głupcami.',
'Największą chlubą nie jest to, aby nigdy się nie potknąć, ale to, aby po każdym upadku dźwignąć się i stanąć na nogi.',
'Największym grzechem jest nie uratować ginącego życia.',
'Najwspanialsza pamięć jest słabsza niż najsłabszy atrament.',
'Najwyższa nawet wieża zaczyna się na ziemi.',
'Najzacniejsi i najmędrsi rodzą się pod strzechami.',
'Należeć do rodu ludzkiego jest łatwo. Być człowiekiem jest trudno.',
'Nawet cesarz ma ubogich krewnych.',
'Nawet jeśli kogoś odprowadza się tysiąc mil, następuje ostateczny moment rozstania.',
'Nawet najczarniejsza chmura ma srebrne brzegi.',
'Nawet w największym gniewie nie składaj skargi do sądu. Nie kradnij, nawet kiedy jesteś najbardziej głodny.',
'Nawet wielki słoń zaplącze się w kobiece włosy.',
'Nerwy jak psa – trzeba trzymać na smyczy, bo mogą rozszarpać człowieka.',
'Nie bij człowieka w bolesną ranę, w kłótni nie dotykaj spraw drażliwych.',
'Nie bój się zmartwień młodości, ale lękaj się biedy na starość.',
'Nie dodając oliwy, nie podkręcaj knota.',
'Nie dogoni i w sto koni dnia, który przeminął.',
'Nie kłóć się z głupim, bo postronni nie zauważą różnicy.',
'Nie ma takiej uczty na świecie, która trwa wiecznie.',
'Nie ma wiatru, nie ma fal.',
'Nie ma większej goryczy od goryczy rozstania się z drogimi.',
'Nie możesz zabronić ptakom smutku krążyć nad twoją głową, ale możesz nie dopuścić do tego, by uwiły gniazdo w twoich włosach.',
'Nie mów dużo, ale powiedz wiele.',
'Nie należy zabijać wołu orzącego ziemię, nie wolno wyrzucać zadrukowanego papieru.',
'Nie naprawiaj statku na środku rzeki.',
'Nie osiągniesz umiejętności bez ćwiczeń.',
'Nie przychodzić do świątyni bez celu.',
'Nie rozlewaj łez zanim nie zobaczysz trumny',
'Nie sądź według pozoru, bo strzała – choć prosta – żądna jest krwi, a lutnia – choć kręta – słodką melodią rozbrzmiewa.',
'Nie sądź, że radość lub złość są dziełem przypadku.',
'Nie sprzedaje się drzewa w lesie ani ryby w jeziorze.',
'Nie szukaj igły w oceanie.',
'Nie trzeba szukać eliksiru nieśmiertelności; genialni ludzie i tak są nieśmiertelni.',
'Nie zawija się ognia w papier.',
'Niebo kocha szczodrego, a nienawidzi skąpca.',
'Niebo nigdy nie zamyka drogi człowiekowi.',
'Nieskończony jest urok dziewicy, nieustanna zazdrość żony.',
'Nieszczęścia pochodzą z naszych ust, choroby też wchodzą ustami.',
'Nieświadomość grzechu nie czyni.',
'Nieważne, kto trzyma krowę za głowę, jeśli to my ją doimy.',
'Nigdy nie łącz się z łotrem, aby drugiego łotra zwyciężyć.',
'Nigdy nie można przewidzieć rano, co się stanie wieczorem.',
'Nigdy nie trzeba mieć tyle rozumu, jak wtedy gdy się ma do czynienia z głupcem.',
'O zajęciach nie mówi się w domu, o kobietach nie mówi się poza domem.',
'Obyś wiecznie czekał!',
'Obyś żył w ciekawych czasach.',
'Oczy widzą prawdę, uszy słyszą fałsz.',
'Od tuszu się uczernisz, cynober zabarwi cię na czerwono.',
'Oddychanie jest panem siły.',
'Oko złodzieja jest bystrzejsze niż oko porządnego człowieka.',
'Oszust nabierze nawet spryciarza.',
'Pewien mąż tak kochał swoją jednooką żonę, że sądził, iż wszystkie inne kobiety mają jedno oko za dużo.',
'Pierwsza rada kobieca – najrozumniejsza; ostatnie ich postanowienie – bardzo niebezpieczne.',
'Pierwsze małżeństwo – z woli rodziców, drugie – z własnej woli.',
'Pies jest wdzięczny za uczucie, a kot za jedzenie.',
'Pies, kiedy go się żywi, wykazuje więcej wdzięczności niż człowiek, któremu się pomaga.',
'Piękna kobieta należy do świata, brzydka tylko do ciebie.',
'Piękną kobietę wychowuje jedna rodzina, a sto rodzin ją pożąda.',
'Piękne słowa nie są wiarygodne, wiarygodne – nie są piękne.',
'Pijanemu niebo i ziemia zdają się olbrzymie, na dnie dzbana dni i miesiące wydają się długie.',
'Pijaństwo tylko ujawnia wady, nie jest ich przyczyną.',
'Po długiej wizycie krótkie pożegnanie.',
'Po jednym spotkaniu, łatwo się zaprzyjaźnić, ale razem mieszkając, łatwo się pokłócić.',
'Po przegranej bitwie dowódca nie chwali się swoimi dawnymi zwycięstwami.',
'Po śmierci zostaje z ducha wiatr, a z ciała – błoto.',
'Po trzech czarkach można pojąć ład rządzący światem, a upicie się rozwiąże tysiąc zmartwień.',
'Po trzech czarkach rozumie się świat, po upiciu giną wszystkie smutki.',
'Po upływie pięciu pokoleń ginie zarówno dobra, jak i zła sława.',
'Po winie cnota ginie.',
'Podejmując coś trudnego, od łatwego najpierw rozpocznij. Zamierzając dokonać czegoś wielkiego, od małego zaczynaj.',
'Podróż o długości tysiąca mil rozpoczyna się od pojedynczego kroku.',
'Podstawą państwa jest lud, a żywność jest dla ludu jak niebo.',
'Pokazując palcem, trzema wskazujesz na siebie.',
'Postanowienia biedaka są krótkotrwałe.',
'Potknąć się można o najzwyklejszą cegłę.',
'Pożądanie jest marnością i marność jest pożądaniem.',
'Prawda jest jak wielka droga, dostępna dla każdego.',
'Prawdziwe słowa nie są piękne, a słowa piękne nie są prawdziwe.',
'Prawo jest jak płot, tygrys przeskoczy, szczur się prześlizgnie, a bydło stoi.',
'Prawo nie karze tłumu.',
'Przemycana sól jest smaczniejsza od sprzedawanej legalnie.',
'Przeszłość się nie skończyła, a przyszłość jeszcze nie nadeszła.',
'Przeszłość, jeśli jej nie zapomnisz, stanie się drogowskazem w przyszłości.',
'Przeżyć Nowy Rok to jakby przeskoczyć przepaść.',
'Przyjaźń wymaga złota.',
'Przyjemności są powierzchowne, ale przykrości sięgają głęboko.',
'Przypadkowe wykroczenie jest błędem, świadome jest winą.',
'Psy odkrywają zające w trawie, wino odkrywa myśli w sercach.',
'Ptak wybiera drzewo, na którym siądzie, ale drzewo nie wybiera ptaka.',
'Pycha przynosi zgubę, skromność i umiarkowanie – ocalenie.',
'Rozum, cnota, dobroć, sprawiedliwość nie są doskonałe bez uprzejmości.',
'Róża jest piękniejsza niż kapusta, lecz zupa z róży jest gorsza niż kapuśniak.',
'Rób to, co lubisz, a nie będziesz musiał pracować',
'Ryba nie powinna opuszczać swych głębin, a polityk nie powinien pokazywać źródeł swych zasobów.',
'Ryż musi mieć nogi w wodzie, a głowę w ogniu.',
'Są dwa rodzaje ludzi dobrych: ci, co umarli, i ci, co się jeszcze nie narodzili.',
'Sąd jednego człowieka nic nie znaczy wobec opinii publicznej.',
'Serce człowieka jest jak żelazo, ale prawo jest jak piec, co je topi.',
'Serce ludu jest sercem niebios.',
'Silny duch lecz wątłe ciało.',
'Słońce doszedłszy do zenitu zniża się, księżyc doszedłszy do pełni zaczyna się zmniejszać.',
'Słowa raz powiedzianego nie cofniesz nawet zaprzęgiem czterech koni.',
'Spiesz się z wykonaniem rzeczy mniej pilnych, by spokojnie zabrać się do najpilniejszych.',
'Spokojna odpowiedź przepędza gniew.',
'Spokojnie rozważaj własne błędy, a w rozmowie nie zajmuj się cudzymi winami.',
'Sprawiedliwość ma siedzibę w ludzkim sercu.',
'Srebro to nawóz, a honor jest więcej wart od tysiąca sztuk złota.',
'Stare chińskie przysłowie mówi: „jeśli nie masz co powiedzieć, powiedz stare chińskie przysłowie”.',
'Starosta rządzi według paragrafów, ale lud ma swoje tajne umowy.',
'Starosta się zmienia, ale pisarze zostają.',
'Starożytni nie oglądali dzisiejszego księżyca, ale dzisiejszy księżyc świecił nad starożytnością.',
'Staw czoła potworowi, a jego potęga zniknie.',
'Sto dzikich kaczek podrywa się nie dlatego, że jedna zakwakała, lecz dlatego, że się poderwała.',
'Strzała zanim wystrzeli do przodu, najpierw musi się znacznie cofnąć.',
'Szczęście się nie powtarza, nieszczęście nie przychodzi pojedynczo.',
'Szczęśliwy lekarz spotyka chorego przy końcu jego choroby, a nieszczęśliwy – przy jej początku.',
'Szlachetny koń nie będzie jadł siana, którego raz mu odmówiono.',
'Szlachetny mąż najpierw działa, potem mówi, a słowa jego zgodne są z czynami.',
'Ślepemu wróblowi Pan Bóg nie pozwoli umrzeć z głodu.',
'Śmiejący się tygrys nie pokazuje zębów.',
'Śniadanie zjedz sam, obiadem podziel się z przyjacielem, a kolację oddaj wrogowi.',
'Ten, co nie wierzy w bogów, wierzy w boga gromu; ten, co nie wierzy w lekarstwa – wierzy w środek na przeczyszczenie.',
'Ten, kto ma wino, powinien pić za życia, bo ani kropla nie przedostanie się na tamten świat.',
'Ten, kto przeniósł górę, zaczął od małych kamyków.',
'Ten, który pyta, pozostaje głupcem przez parę chwil, lecz ten, który nie zadaje pytań, będzie nim zawsze.',
'To nie wino upija człowieka, to człowiek upija się sam.',
'To, co się powie człowiekowi prosto w twarz – nie jest plotką.',
'Trudności od prawdy nie oddzielisz nożem.',
'Trzeba uważać śmierć za powrót do poprzedniego stanu.',
'Trzeba zamącić wodę w stawie, żeby złapać rybę.',
'Trzy dni bez lektury i nasze rozmowy stają się jałowe.',
'Trzy razy pomyśl, zanim coś zrobisz, a nie będziesz żałował swych czynów.',
'Trzyletni chłopiec kupuje trumnę, bo wie, co go prędzej czy później czeka.',
'Tygrys gryzie za grzechy popełnione siedem pokoleń wstecz.',
'Tylko ci, co robią powoli to, co inni robią w pośpiechu, są w stanie zrobić prędko to, co inni muszą robić powoli.',
'Tylko oczyma drugich możemy dostrzec własne błędy.',
'Tysiąc dni karmi się żołnierza na jeden dzień bitwy.',
'Uczony jest skarbem swojego kraju.',
'Uderzyć włąsną włócznią w swoją tarczę.',
'Umierający ptak wydaje żałosne dźwięki; umierający człowiek wygłasza mądre zdania.',
'Umysł kobiety – żywe srebro; ich serca to wosk.',
'Uroda nie kusi, to ludzie się kuszą; wino nie upija, to ludzie się upijają.',
'Urojonej choroby nie wyleczy się lekarstwami; prawdziwego zmartwienia nie utopi się w winie.',
'Urzędnik nigdy nie ma wolnego czasu, mnich stale próżnuje.',
'Usta namaszczone olejem, a serce ostre jak brzytwa.',
'W dniu twych narodzin wszyscy byli weseli, tylko ty płakałeś. Żyj tak, by w twej ostatniej godzinie płakali wszyscy inni, a ty jeden byś się śmiał serdecznie i łzy nie miał w oku.',
'W zbyt czystej wodzie nie ma ryb.',
'W domu są rodzinne zasady, w sklepie – kupieckie obyczaje.',
'W małżeństwie nikt nie mówi prawdy, przed przyjaciółmi nikt nie kłamie.',
'W nauce wiek się nie liczy, zdolności mają pierwszeństwo.',
'W obliczu śmierci głodowej nikt nie zachowa etykiety.',
'W płytkiej wodzie raki będą się wyśmiewać ze smoka, a na równinie psy nie będą drażnić się z tygrysem.',
'W potrzebie nawet wilka można odpędzić zwykłą wiązką konopi.',
'W stanowieniu praw konieczna jest surowość, a miłosierdzie – w ich stosowaniu.',
'W zimie nie pożyczaj ubrania, a w lecie wachlarza.',
'Wąż nie zmieni swojej krętej natury, nawet kiedy się wśliźnie w prostą rurę bambusową.',
'We fragmentach, prawdy mało, albo nie ma prawdy wcale.',
'Widzimy, jak złoczyńcy ucztują, ale nie widzimy, jak ich karzą.',
'Wiedza to skarb, który zawsze podąża za tym, kto go posiada.',
'Wiedza i doświadczenie przychodzą z wiekiem. Najczęściej jest to wieko od trumny.',
'Wieku nie starczy na budowanie; żeby zburzyć – jeden dzień wystarczy.',
'Wielka rzecz umieć czekać.',
'Wielkie bóstwo nie pamięta o małych grzechach.',
'Wierny minister nie służy dwóm panom; cnotliwa żona nie wychodzi za drugiego męża.',
'Wierny poddany nie boi się śmierci; jeśli boi się śmierci – nie jest wiernym poddanym.',
'Wierzyć w Tao jest łatwo, ale przyjąć Tao jest trudno.',
'Wino pije się z przyjaciółmi, wiersze czyta się przed znawcami.',
'Władza pochodząca z jednego źródła jest mocna, ale gdy pochodzi z dwóch źródeł, jest słaba.',
'Wół jest powolny ale ziemia cierpliwa.',
'Wróbel jest małym ptaszkiem, ale ma wątrobę i żółć.',
'Współwyznawcy kochają się, biznesmeni nie ufają sobie wzajemnie.',
'Wstrzemięźliwy człowiek z czerwonym nosem uchodzi za pijaka.',
'Wstyd jest męstwem płci pięknej, milczenie i rumieniec – wymową.',
'Wszyscy depczą mur przewrócony i w dziurawy bęben walą.',
'Wszyscy ludzie są mądrzy: jedni przedtem, inni potem.',
'Wykorzystaj swoje silne punkty do ataku na słabe punkty przeciwnika.',
'Wysoko w niebo wzbija się dym z komina, jeżeli wszyscy w rodzinie zbierają chrust.',
'Wystarczy kobiecie trzy razy powiedzieć, że jest ładna, aby za pierwszym razem podziękowała, uwierzyła za drugim, a wynagrodziła za trzecim.',
'Z dobrego żelaza nie robi się gwoździa, z dobrego człowieka nie robi się żołnierza.',
'Z mordercą swego ojca nie będziesz żył pod tym samym niebem,',
'Z poetami, malarzami i muzykami jest tak samo jak z grzybami: wśród dziesięciu tysięcy jeden dobry.',
'Z rana przyjaciele, wieczorem wrogowie.',
'Za krzywdę płać sprawiedliwością, łaskę opłacaj łaską.',
'Za mord trzeba dać życie, za pożyczkę trzeba zwrócić pieniądze.',
'Zacni długo nie żyją.',
'Zadaniem sieci jest złapanie ryb,',
'A kiedy złapie się ryby o sieci się zapomina.',
'Zadaniem potrzasku jest złapanie królika,',
'A gdy złapie się królika o potrzasku się zapomina.',
'Zadaniem słów jest złapanie idei,',
'A gdy uchwyci się idee, słów się zapomina.',
'Gdzie znajdę tego, który zapomniał słów?',
'To z nim chcę rozmawiać.',
'Zamiast innych się radzić, radź się samego siebie.',
'Zamożność uzyskana z ziemi trwa tysiąc lat, a zyski z urzędu są przemijającym dymem.',
'Zanim się pojawi cesarz, już są dworacy.',
'Zanim zaczniesz poprawiać świat, przejdź się trzy razy przez swój własny dom.',
'Zbłądziwszy na drodze zawsze można zawrócić, ale fałszu nie można cofnąć.',
'Zbytnia skrupulatność jest sprzeczna z rozsądkiem.',
'Zdejmując buty wieczorem, nie wiesz, czy je włożysz rano.',
'Zjesz niegotowane mięso – zaszkodzi żołądkowi. Powiesz nieprzyzwoite słowo – zaszkodzi całemu tobie.',
'Zły mąż bywa niekiedy dobrym ojcem, zła żona nigdy nie będzie dobrą matką.',
'Zły syn kocha żonę i sprzeciwia się matce, niedobra matka dręczy synową.',
'Znaj wroga i samego siebie, a możesz stoczyć 100 bitew nie wiedząc co to porażka.',
'Związanego łatwo bić.',
'Zwyczaj wpływa na wszystkich, i nikt mu się nie może oprzeć.',
'Zwykle mąż i żona żyją jak dwa ptaszki w tym samym lesie, ale w nieszczęściu rozlatują się, każde w swoją stronę.',
'Żaba na dnie studni nigdy nie zobaczy morskich fal.',
'Żołądek pełen lekarstw i koszula łatana długo nie wytrzymują,',
'Żony szukamy dla jej cnoty, a nałożnicy dla jej urody.',
'Życie człowieka jest jak sen wiosenny, a bogactwa i zaszczyty jak przemijające chmurki.',
'Żyj tak, jakbyś miał umrzeć jutro, a pracuj tak jakbyś miał przed sobą wieczność.'
	]
}